# Generated by Django 4.2.1 on 2023-05-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
